---
title: "Stage_M2_NB-3-FST"
author: "Nicolas Bettembourg"
date: "2024-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## FST plot

### Création du fichier FST ind2pop - Merged Data - SeqApiPop BeeMuSe

```{r}
#output_list_1_merged.txt
setwd("~/Documents/Stage_NB/data/merged_BeeMuSe_SeqApiPop_629_filtered_maf001_LD03") #2 premières colonnes .fam

ind2pop_merged_data <- read.table("ind2pop_merged_data.txt", header = FALSE)

# Remplacement de la deuxième colonne par les valeurs spécifiées
ind2pop_merged_data$V2 <- ind_pop

write.table(ind2pop_merged_data, "ind2pop_merged_data_3.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
```

```{r}
setwd("~/Documents/Stage_NB/data/merged_BeeMuSe_SeqApiPop_629_filtered_maf001_LD03") 
fst_file <- read.table("ind2pop_seqapipop_629_fst.txt", header = FALSE)
print(unique(fst_file$V2))

fst_file <- cbind(fst_file[, "V1"], fst_file, fst_file[, "V1"])

# Remove the original V1 column
fst_file <- fst_file[, -4]

# Rename the duplicated V1 column to V2
names(fst_file)[1] <- "V1"
names(fst_file)[2] <- "V2"
names(fst_file)[3] <- "V3"

write.table(fst_file, "ind2pop_seqapipop_629_fst_2.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
```

### **SeqApiPop 629 échantillons**

```{r}
setwd("~/Documents/Stage_NB/data/fst_files") 
# Charger les données
fst_data_SeqApiPop_629 <- read.table("SeqApiPop_629_fst.fst", header=TRUE)

fstsubset <- fst_data_SeqApiPop_629[complete.cases(fst_data_SeqApiPop_629),]
SNP <- c(1:(nrow(fstsubset)))
mydf <- data.frame(SNP, fstsubset)
 
manhattan(mydf,chr="CHR",bp="POS",p="FST",snp="SNP",logp=FALSE,ylab="Fst")

# Nuage de points
plot(fst_data_SeqApiPop_629$POS, fst_data_SeqApiPop_629$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
# Histogramme
barplot(fst_data_SeqApiPop_629$FST, names.arg=fst_data_SeqApiPop_629$POS, xlab="Position (POS)", ylab=" Fst", main="Graphique FST")

# Créer un violin plot des valeurs de FST
vioplot(fst_data_SeqApiPop_629$FST, names="FST", col="#FF0000",ylim=c(0, 1), horizontal=FALSE, main="Violin Plot FST - SeqApiPop_629")
```

#### SeqApiPop 629 échantillons - MAF \> 0.01

```{r}
setwd("~/Documents/Stage_NB/data/fst_files") 
# Charger les données
fst_data_SeqApiPop_629_maf001 <- read.table("SeqApiPop_629_maf001_fst.fst", header=TRUE)

fstsubset2 <- fst_data_SeqApiPop_629_maf001[complete.cases(fst_data_SeqApiPop_629_maf001),]
SNP2 <- c(1:(nrow(fstsubset2)))
mydf2 <- data.frame(SNP2, fstsubset2)
 
manhattan(mydf2,chr="CHR",bp="POS",p="FST",snp="SNP",logp=FALSE,ylab="Fst")

# Nuage de points
plot(fst_data_SeqApiPop_629_maf001$POS, fst_data_SeqApiPop_629_maf001$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
# Histogramme
barplot(fst_data_SeqApiPop_629_maf001$FST, names.arg=fst_data_SeqApiPop_629_maf001$POS, xlab="Position (POS)", ylab=" Fst", main="Graphique FST")

# Créer un violin plot des valeurs de FST
vioplot(fst_data_SeqApiPop_629_maf001$FST, names="FST", col="#FFA500",ylim=c(0, 1), horizontal=FALSE, main="Violin Plot FST - SeqApiPop_629_maf001")
```

#### SeqApiPop 629 échantillons - MAF \> 0.01 - LD pruning = 0.3 (fenêtre de 1749 SNPs et pas de 175 bp)

```{r}
setwd("~/Documents/Stage_NB/data/fst_files") 
# Charger les données
fst_data_SeqApiPop_629_maf001_LD03 <- read.table("SeqApiPop_629_maf001_LD03_pruned_fst.fst", header=TRUE)

fstsubset3 <- fst_data_SeqApiPop_629_maf001_LD03[complete.cases(fst_data_SeqApiPop_629_maf001_LD03),]
SNP3 <- c(1:(nrow(fstsubset3)))
mydf3 <- data.frame(SNP3, fstsubset3)
 
manhattan(mydf3,chr="CHR",bp="POS",p="FST",snp="SNP",logp=FALSE,ylab="Fst")

# Nuage de points
plot(fst_data_SeqApiPop_629_maf001_LD03$POS, fst_data_SeqApiPop_629_maf001_LD03$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
# Histogramme
barplot(fst_data_SeqApiPop_629_maf001_LD03$FST, names.arg=fst_data_SeqApiPop_629_maf001_LD03$POS, xlab="Position (POS)", ylab=" Fst", main="Graphique FST")

# Créer un violin plot des valeurs de FST
vioplot(fst_data_SeqApiPop_629_maf001_LD03$FST, names="FST", col="#FFFF00",ylim=c(0, 1), horizontal=FALSE, main="Violin Plot FST - SeqApiPop_629_maf001_LD03")
```

```{r}
# Création d'une variable pour chaque jeu de données
fst_data_SeqApiPop_629$Group <- "seqapipop_629"
fst_data_SeqApiPop_629_maf001$Group <- "seqapipop_629_maf001"
fst_data_SeqApiPop_629_maf001_LD03$Group <- "seqapipop_629_maf001_LD03"

# Combiner les jeux de données en un seul dataframe
combined_data <- rbind(fst_data_SeqApiPop_629, fst_data_SeqApiPop_629_maf001, fst_data_SeqApiPop_629_maf001_LD03)

# Changer le type de la variable 'Group' en factor avec l'ordre spécifié
combined_data$Group <- factor(combined_data$Group, levels = group_order)

# Créer le violin plot avec ggplot
ggplot(combined_data, aes(x = Group, y = FST, fill = Group)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1) +
  scale_fill_manual(values = c("seqapipop_629" = "#FF0000", 
                               "seqapipop_629_maf001" = "#FFA500", 
                               "seqapipop_629_maf001_LD03" = "#FFFF00")) +
  labs(title = "Violin Plot of FST values",
       x = "Group",
       y = "FST") +
  theme_minimal()
```

#### SeqApiPop 629 échantillons - SNPsBeeMuSe filtered

##### 10030 SNPs

```{r}
setwd("~/Documents/Stage_NB/data/SeqApiPop_629_SNPsBeeMuSe") 

# Charger les données
fst_data_10030 <- read.table("SeqApiPop_629_SNPsBeeMuSe_filtered_fst.fst", header=TRUE)

fstsubset <- fst_data_10030[complete.cases(fst_data_10030),]
SNP <- c(1:(nrow(fstsubset)))
mydf <- data.frame(SNP, fstsubset)
 
manhattan(mydf,chr="CHR",bp="POS",p="FST"
,snp="SNP",logp=FALSE,ylab="Fst")

# Nuage de points
#plot(fst_data_10030$POS, fst_data_10030$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
# Histogramme
#barplot(fst_data_10030$FST, names.arg=fst_data_10030$POS, xlab="Position (POS)", ylab=" Fst", main="Graphique FST")

# Créer un violin plot des valeurs de FST
vioplot(fst_data_10030$FST, names="FST", col="#1f77b4",ylim=c(0, 1), horizontal=FALSE, main="Violin Plot FST - 10030 SNPs")

# Filtrer les données pour inclure uniquement les positions du chromosome 11
fst_data_10030_chr11 <- subset(fst_data_10030, CHR == "11")

SNP <- seq_len(nrow(fst_data_10030_chr11))
mydf_11 <- data.frame(SNP = SNP, fst_data_10030_chr11)
manhattan(mydf_11, chr = "CHR", bp = "POS", p = "FST", snp = "SNP", logp = FALSE, ylab = "Fst")

#plot(fst_data_10030_chr11$POS, fst_data_10030_chr11$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
#barplot(fst_data_10030_chr11$FST, names.arg=fst_data_10030_chr11$POS, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
vioplot(fst_data_10030_chr11$FST, names="FST", col="#aec7e8", ylim=c(0, 1),horizontal=FALSE, main="Violin Plot FST - Chr 11 - 10030 SNPs")
```

##### 3848 SNPs

```{r}
setwd("~/Documents/Stage_NB/data/SeqApiPop_629_SNPsBeeMuSe") 

# Charger les données
fst_data_3848 <- read.table("SeqApiPop_629_SNPsBeeMuSe_filtered_maf001_LD03_pruned_fst.fst", header=TRUE)


fstsubset <- fst_data_3848[complete.cases(fst_data_3848),]
SNP <- c(1:(nrow(fstsubset)))
mydf <- data.frame(SNP, fstsubset)
 
manhattan(mydf,chr="CHR",bp="POS",p="FST"
,snp="SNP",logp=FALSE,ylab="Fst")

# Nuage de points
#plot(fst_data_3848$POS, fst_data_3848$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
# Histogramme
#barplot(fst_data_3848$FST, names.arg=fst_data_3848$POS, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")

vioplot(fst_data_3848$FST, names="FST", col="#d62728", ylim=c(0, 1),horizontal=FALSE, main="Violin Plot FST - 3848 SNPs")

# Filtrer les données pour inclure uniquement les positions du chromosome 11
fst_data_3848_chr11 <- subset(fst_data_3848, CHR == "11")

SNP <- seq_len(nrow(fst_data_3848_chr11))
mydf_11 <- data.frame(SNP = SNP, fst_data_3848_chr11)
manhattan(mydf_11, chr = "CHR", bp = "POS", p = "FST", snp = "SNP", logp = FALSE, ylab = "Fst")

#plot(fst_data_3848_chr11$POS, fst_data_3848_chr11$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
#barplot(fst_data_3848_chr11$FST, names.arg=fst_data_3848_chr11$POS, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
vioplot(fst_data_3848_chr11$FST, names="FST", col="#ff9896",ylim=c(0, 1), horizontal=FALSE, main="Violin Plot FST - Chr 11 - 3848 SNPs")
```

##### 1055 SNPs

```{r}
setwd("~/Documents/Stage_NB/data/SeqApiPop_629_SNPsBeeMuSe") 

# Charger les données
fst_data_1055 <- read.table("SeqApiPop_629_SNPsBeeMuSe_filtered_maf001_LD03_default_pruned_fst.fst", header=TRUE)


fstsubset <- fst_data_1055[complete.cases(fst_data_1055),]
SNP <- c(1:(nrow(fstsubset)))
mydf <- data.frame(SNP, fstsubset)
 
manhattan(mydf,chr="CHR",bp="POS",p="FST"
,snp="SNP",logp=FALSE,ylab="Fst")

# Nuage de points
#plot(fst_data_1055$POS, fst_data_1055$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
# Histogramme
#barplot(fst_data_1055$FST, names.arg=fst_data_1055$POS, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")

vioplot(fst_data_1055$FST, names="FST", col="#FFA500", ylim=c(0, 1),horizontal=FALSE, main="Violin Plot FST - 3848 SNPs")

# Filtrer les données pour inclure uniquement les positions du chromosome 11
fst_data_1055_chr11 <- subset(fst_data_1055, CHR == "11")

SNP <- seq_len(nrow(fst_data_1055_chr11))
mydf_11 <- data.frame(SNP = SNP, fst_data_1055_chr11)
manhattan(mydf_11, chr = "CHR", bp = "POS", p = "FST", snp = "SNP", logp = FALSE, ylab = "Fst")

#plot(fst_data_1055_chr11$POS, fst_data_1055_chr11$FST, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
#barplot(fst_data_1055_chr11$FST, names.arg=fst_data_1055_chr11$POS, xlab="Position (POS)", ylab="Valeurs FST", main="Graphique FST")
vioplot(fst_data_1055_chr11$FST, names="FST", col="#ffcc7a",ylim=c(0, 1), horizontal=FALSE, main="Violin Plot FST - Chr 11 - 3848 SNPs")
```

```{r}
# Création d'un facteur pour distinguer les différentes données
fst_data_10030$Dataset <- "fst_data_10030"
fst_data_10030_chr11$Dataset <- "fst_data_10030_chr11"
fst_data_3848$Dataset <- "fst_data_3848"
fst_data_3848_chr11$Dataset <- "fst_data_3848_chr11"
fst_data_1055$Dataset <- "fst_data_1055"
fst_data_1055_chr11$Dataset <- "fst_data_1055_chr11"

fst_dataset <- rbind(fst_data_10030, fst_data_10030_chr11, fst_data_3848, fst_data_3848_chr11, fst_data_1055, fst_data_1055_chr11)

# Define the order of groups
group_order <- c("fst_data_10030", "fst_data_10030_chr11", 
                 "fst_data_3848", "fst_data_3848_chr11", 
                 "fst_data_1055", "fst_data_1055_chr11")
# Convert Group column to factor with custom levels
fst_dataset$Dataset <- factor(fst_dataset$Dataset, levels = group_order)

# Create the violin plot with y-axis limits set from 0 to 1
ggplot(fst_dataset, aes(x = Dataset, y = FST, fill = Dataset)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1) +
  scale_fill_manual(values = c("fst_data_10030" = "#1f77b4", 
                               "fst_data_10030_chr11" = "#aec7e8", 
                               "fst_data_3848" = "#d62728",
                               "fst_data_3848_chr11" = "#ff9896",
                               "fst_data_1055" = "#FFA500",
                               "fst_data_1055_chr11" = "#ffcc7a")) +
  labs(title = "Violin Plot of FST values",
       x = "Group",
       y = "FST") +
  theme_minimal() +
  ylim(0, 1) 


# Calculate mean values for each dataset
mean_values <- aggregate(FST ~ Dataset, data = fst_dataset, FUN = mean)

# Print mean values
print(mean_values)
```

## 
